name: CI

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

env:
  JULIA_PKG_SERVER: internal.juliahub.com

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}

    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10.8'
          - '1.11.3'
        os:
          - self-hosted
        arch:
          - x64

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: julia-actions/setup-julia@5c9647d97b78a5debe5164e9eec09d653d29bd71 # v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - name: "Set up private JuliaHub registries"
        uses: "JuliaComputing/set-up-private-juliahub-registries@a60c35b0463eb38fcb438d0222ca56ce422d970a" # v1.2.1
        with:
          encoded-juliahub-token: "${{ secrets.JULIAHUB_TOKEN_ENCODED }}"
          ssh-key: "${{ secrets.JULIASIM_REGISTRY_SSH_KEY }}"
          enable-JSMLComponents: "true"

      - uses: julia-actions/julia-buildpkg@e3eb439fad4f9aba7da2667e7510e4a46ebc46e1 # v1

      - uses: julia-actions/julia-runtest@678da69444cd5f13d7e674a90cb4f534639a14f9 # v1
